---
# Retrieve the current hostname, because {{ ansible_hostname }} still contains the old name
- name: mysql | Install MySQL Packages
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - mysql-server
    - mysql-client
    - python-mysqldb

- name: copy .my.cnf file with root password credentials
  template:
    src: .my.cnf
    dest: ~/.my.cnf
    owner: root
    mode: 0600

- name: Update MySQL root password for all root accounts
  sudo: yes
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "root"
    login_user: root
    login_password: "root"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: Setup MySQL user for WordPress
  mysql_user: name=wordpress password=wordpress priv=*.*:ALL state=present