---
- hosts: all
  sudo: true

  vars:
    apache_vhosts_enabled:
      - servername: "cu-local.carleton.ca"
        documentrootdir: "cu-local"
        dbname: "cu-local"
        errorlog: "cu-local"
        customlog: "cu-local"
      - servername: "ccms-local.carleton.ca"
        documentrootdir: "ccms-local"
        dbname: "ccms-local"
        errorlog: "ccms-local"
        customlog: "ccms-local"
      - servername: "framework-local.carleton.ca"
        documentrootdir: "framework-local"
        dbname: "framework-local"
        errorlog: "framework-local"
        customlog: "framework-local"
      - servername: "intranet-local.carleton.ca"
        documentrootdir: "intranet-local"
        dbname: "intranet-local"
        errorlog: "intranet-local"
        customlog: "intranet-local"

  roles:
   - apache
   - mysql
   - php
   - wp-cli
   - pma
   - xdebug
   - mailcatcher
   - vhost-db
   - webgrind
   - temp-page
